version: '3'

services:
  feiyangdigital-bot:
    image: youshandefeiyang/feiyangdigital-bot:latest # 使用您在DockerHub上的镜像
    ports:
      - "38455:8080"
    volumes:
      - /home/feiyangdigitalbotconf/config.json:/app/config.json
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bot?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --skip-bind-address
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bot
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
      - /home/feiyangdigitalbotconf/bot.sql:/docker-entrypoint-initdb.d/bot.sql
    restart: unless-stopped

  redis:
    image: redis:latest
    command:
      - --save 900 1
      - --save 300 10
      - --save 60 10000
      - --rdbcompression yes
      - --rdbchecksum yes
      - --dbfilename dump.rdb
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:
